{{- if and .Values.persistence.transfer.enabled (not .Values.persistence.transfer.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "coder.transferClaimName" . }}
  labels:
    {{- include "coder.labels" . | nindent 4 }}
    {{- with .Values.persistence.transfer.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.persistence.transfer.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.transfer.accessModes | nindent 4 }}
  volumeMode: {{ .Values.persistence.transfer.volumeMode }}
  {{- if .Values.persistence.transfer.storageClass }}
  storageClassName: {{ .Values.persistence.transfer.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.transfer.size | quote }}
{{- end }}

