{{- if and .Values.persistence.home.enabled (not .Values.persistence.home.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "coder.homeClaimName" . }}
  labels:
    {{- include "coder.labels" . | nindent 4 }}
    {{- with .Values.persistence.home.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.persistence.home.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.home.accessModes | nindent 4 }}
  volumeMode: {{ .Values.persistence.home.volumeMode }}
  {{- if .Values.persistence.home.storageClass }}
  storageClassName: {{ .Values.persistence.home.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.home.size | quote }}
{{- end }}

