apiVersion: v2
name: gpubox
description: Privileged GPU devbox StatefulSet (VS Code CLI tunnel)
type: application
version: 0.2.2
appVersion: "24.04-vscodecli-1.108.2"
keywords:
  - vscode
  - tunnel
  - gpu
  - devbox
  - privileged
